name: Lint
on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Enable Corepack and Setup Yarn
      run: |
        corepack enable
        corepack prepare yarn@4.6.0 --activate
        yarn set version 4.6.0
        yarn --version
    - name: Install dependencies
      run: yarn install --immutable
    - name: Run lint
      run: yarn lint
